server:
  http_listen_port: 3200

storage:
  trace:
    backend: azureblob
    azureblob:
      container: "tempo-traces"
      account_name: "beez360storage"
      account_key: "${data.azurerm_storage_account_keys.beez360.keys[0].value}"


  index:
    prefix: "tempo_index_"
    period: 24h
    store: azureblob
    azureblob:
      container: "tempo-index"
      account_name: "beez360storage"
      account_key: "${data.azurerm_storage_account_keys.beez360.keys[0].value}"



sampling:
  default_strategy:
    probabilistic:
      sampling_rate: 0.05
