{
 "title": "Node Exporter AND LOG Dashboard",
 "description": "This dashboard mainly displays host monitoring indicators and logs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "IP", "query": { "query": "label_values(instance)" } },
   { "name": "interval", "label": "间隔", "query": "1m,2m,3m,5m,10m,30m" },
   {
    "name": "job",
    "label": "日志",
    "query": {}
   },
   {
    "name": "LogFile",
    "label": "文件",
    "query": {}
   },
   { "name": "search", "label": "查询" }
  ]
 },
 "panels": [
  { "title": "资源总览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "服务器",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 1 },
   "targets": [
    { "expr": "node_uname_info{} - 0", "legendFormat": "系统信息" },
    {
     "expr": "sum(time() - node_boot_time_seconds{})by(instance)/86400",
     "legendFormat": "运行时间"
    },
    {
     "expr": "((1-(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) by (instance))^1.3)^(1/3)*0.5 + \r\n(1-(1 - avg(node_memory_MemAvailable_bytes{} / node_memory_MemTotal_bytes{})by (instance))^6)^(1/3)*0.3 + \r\n(1 - max(irate(node_disk_io_time_seconds_total{}[$interval]))by (instance)^1.1)^(1/2)*0.2)*100",
     "legendFormat": "健康度"
    },
    { "expr": "node_load5{}", "legendFormat": "5分钟负载" },
    {
     "expr": "count(node_cpu_seconds_total{mode='system'}) by (instance)",
     "legendFormat": "cpu核数"
    },
    {
     "expr": "node_memory_MemTotal_bytes{} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "cpu使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes))) * 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max(rate(node_disk_io_time_seconds_total[$interval])) by (instance) * 100",
     "legendFormat": "IO使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total[$interval])) by (instance)",
     "legendFormat": "写入"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total[$interval])) by (instance)",
     "legendFormat": "读取"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total[$interval]))by (instance)",
     "legendFormat": "下载"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total[$interval])) by (instance)",
     "legendFormat": "上传"
    }
   ]
  },
  { "title": "实例资源 $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance:9100\"}[$interval])) by (instance) *100",
     "legendFormat": "系统使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance:9100\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "用户使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$instance:9100\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "磁盘io使用率"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$instance:9100\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "总使用率"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$instance:9100\"} ",
     "legendFormat": "总内存"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=~\"$instance:9100\"} - node_memory_MemAvailable_bytes{instance=~\"$instance:9100\"})",
     "legendFormat": "已用"
    },
    {
     "expr": "(node_memory_MemAvailable_bytes{instance=~\"$instance:9100\"})",
     "legendFormat": "可用"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$instance:9100\"} / (node_memory_MemTotal_bytes{instance=~\"$instance:9100\"})))* 100",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "日志 ：$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "日志面板",
     "type": "logs",
     "gridPos": { "h": 24, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "{hostname=\"$instance\", job=\"$job\",filename=\"$LogFile\"} |~ \"$search\"",
       "legendFormat": "日志",
       "maxLines": 500
      }
     ]
    }
   ]
  }
 ]
}