{
 "title": "Beez360 Api Visualization",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Nombre des requêtes ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance_name) (increase(appservice_request_count{instance_name=\"beez360-frc-franchisee-paris-dev-api-webapp\"}[1h]))",
     "legendFormat": "nombre de requetes"
    }
   ]
  },
  {
   "title": "cpu time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "appservice_cpu_time{instance_name=\"beez360-frc-franchisee-paris-dev-api-webapp\"}",
     "legendFormat": "cpu time "
    }
   ]
  },
  {
   "title": "Nombre de logs Info & error",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"eventhub\"}[1h])"
    }
   ]
  },
  {
   "title": "Memory Working Set",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 3, "y": 16 },
   "targets": [
    {
     "expr": "appservice_memory_working_set{instance_name=\"beez360-frc-franchisee-paris-dev-api-webapp\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"eventhub\"} | json"
    }
   ]
  }
 ]
}