{
 "title": "Logs of BackOffice App",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Nombre des logs Info par heure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"azure-webapp\", resourceId=~\".*BACKOFFICE.*\"}  |= `info` [1h])",
     "legendFormat": "Nombre des logs Info par heure"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"azure-webapp\", resourceId=~\".*BACKOFFICE.*\"}  |= `Info` [1h])",
     "legendFormat": "Nombre des logs Info par heure"
    }
   ]
  },
  {
   "title": "Nombre des logs error par heure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({resourceId=\"/SUBSCRIPTIONS/7DF6C09E-5B30-41D7-8BF2-D39B61F07DE3/RESOURCEGROUPS/BEEZ360-FRC-FRANCHISEE-PARIS-DEV-RG/PROVIDERS/MICROSOFT.WEB/SITES/BEEZ360-FRC-FRANCHISEE-PARIS-DEV-BACKOFFICE-WEBAPP\"} |= `error` [1h])",
     "legendFormat": "Nombre des logs par heure"
    },
    {
     "direction": "backward",
     "expr": "count_over_time({resourceId=\"/SUBSCRIPTIONS/7DF6C09E-5B30-41D7-8BF2-D39B61F07DE3/RESOURCEGROUPS/BEEZ360-FRC-FRANCHISEE-PARIS-DEV-RG/PROVIDERS/MICROSOFT.WEB/SITES/BEEZ360-FRC-FRANCHISEE-PARIS-DEV-BACKOFFICE-WEBAPP\"} |= `Error` [1h])",
     "legendFormat": "Nombre des logs par heure"
    }
   ]
  },
  {
   "title": "Cpu Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "appservice_cpu_time{instance_name=\"beez360-frc-franchisee-paris-dev-backoffice-webapp\"}",
     "legendFormat": "Cpu Time In BackOffice"
    }
   ]
  },
  {
   "title": "Working Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "appservice_memory_working_set{instance_name=\"beez360-frc-franchisee-paris-dev-backoffice-webapp\"}",
     "legendFormat": "memory working set in the BackOffice"
    }
   ]
  },
  {
   "title": "Info Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"azure-webapp\", resourceId=~\".*BACKOFFICE.*\"} |= `info` | json"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"azure-webapp\", resourceId=~\".*BACKOFFICE.*\"} |= `ERROR` | json"
    },
    {
     "direction": "backward",
     "expr": "{job=\"azure-webapp\", resourceId=~\".*BACKOFFICE.*\"} |= `Error` | json"
    },
    {
     "direction": "backward",
     "expr": "{job=\"azure-webapp\", resourceId=~\".*BACKOFFICE.*\"} |= `error` | json"
    }
   ]
  }
 ]
}