{
 "title": "Logs Of Click & Collect WebApp",
 "description": "Dashboard monitoring Beez360 : logs (error/info) et métriques CPU, mémoire, etc.",
 "tags": [
  "monitoring",
  "logs",
  "prometheus",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Nombre de logs Error par heure de C&C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"azure-webapp\", resourceId=~\".*CLICKANDCOLLECT.*\"} |= `Error` [1h])"
    }
   ]
  },
  {
   "title": "Nombre de logs Info par heure de C&C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"azure-webapp\", resourceId=~\".*CLICKANDCOLLECT.*\"} |= `info` [1h])"
    }
   ]
  },
  {
   "title": "Logs Click & Collect - Erreur",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"azure-webapp\", resourceId=~\".*CLICKANDCOLLECT.*\"} |= `ERROR`"
    },
    {
     "direction": "backward",
     "expr": "{job=\"azure-webapp\", resourceId=~\".*CLICKANDCOLLECT.*\"} |= `Error`"
    },
    {
     "direction": "backward",
     "expr": "{job=\"azure-webapp\", resourceId=~\".*CLICKANDCOLLECT.*\"} |= `error`"
    }
   ]
  },
  {
   "title": "Logs Click & Collect - Info",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=\"azure-webapp\", resourceId=~\".*CLICKANDCOLLECT.*\"} |= `info` | json\r\n| line_format \"{{.time}} {{if .CsMethod}}HTTP {{.CsMethod}} {{.CsUriStem}} {{.ScStatus}}{{else}}APP {{.message}}{{end}}\""
    },
    {
     "direction": "backward",
     "expr": "{job=\"azure-webapp\", resourceId=~\".*CLICKANDCOLLECT.*\"} |= `Info` | json\r\n| line_format \"{{.time}} {{if .CsMethod}}HTTP {{.CsMethod}} {{.CsUriStem}} {{.ScStatus}}{{else}}APP {{.message}}{{end}}\""
    },
    {
     "direction": "backward",
     "expr": "{job=\"azure-webapp\", resourceId=~\".*CLICKANDCOLLECT.*\"} |= `informational` | json\r\n| line_format \"{{.time}} {{if .CsMethod}}HTTP {{.CsMethod}} {{.CsUriStem}} {{.ScStatus}}{{else}}APP {{.message}}{{end}}\""
    }
   ]
  }
 ]
}