{
 "title": "Home Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Categorisation des ressources",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(acr_pull_count)", "legendFormat": "__auto" },
    {
     "expr": "count(appservice_request_count)",
     "legendFormat": "Webapps"
    },
    { "expr": "count(appplan_cpu_percentage)", "legendFormat": "AppPlans" },
    { "expr": "count(postgresql_cpu_percent)", "legendFormat": "Postgres" },
    { "expr": "count(storage_used_capacity)", "legendFormat": "Compte de stockage" },
    {
     "expr": "count(keyvault_service_api_hit)",
     "legendFormat": "Container Registry"
    }
   ]
  },
  {
   "title": "Error Logs ",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"eventhub\"} |~ `(error|Error|ERROR)` [1h])",
     "legendFormat": "Api Errors"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\r\n  {job=\"azure-webapp\", resourceId=~\".*BACKOFFICE.*\"}\r\n  |~ \"(error|Error|ERROR)\"\r\n[1h])",
     "legendFormat": "BackOffice Errors"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\r\n  {job=\"azure-webapp\", resourceId=~\".*CLICKANDCOLLECT.*\"}\r\n  |~ \"(error|Error|ERROR)\"\r\n[1h])",
     "legendFormat": "Click&Collect Errors"
    }
   ]
  },
  {
   "title": "Info Logs ",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time({job=\"eventhub\"} |~ `(info|INFO|Info)` [1h])",
     "legendFormat": "Api Info"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\r\n  {job=\"azure-webapp\", resourceId=~\".*BACKOFFICE.*\"}\r\n  |~ \"(Info|info|INFO)\"\r\n[1h])",
     "legendFormat": "BackOffice Info"
    },
    {
     "direction": "backward",
     "expr": "count_over_time(\r\n  {job=\"azure-webapp\", resourceId=~\".*CLICKANDCOLLECT.*\"}\r\n  |~ \"(info|INFO|Info)\"\r\n[1h])",
     "legendFormat": "Click&Collect Info"
    }
   ]
  },
  {
   "title": "Nombre des Requetes par WebApp",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance_name) (increase(appservice_request_count{instance_name=\"beez360-frc-franchisee-paris-dev-api-webapp\"}[1h]))",
     "legendFormat": "Api"
    },
    {
     "expr": "sum by(instance_name) (increase(appservice_request_count{instance_name=\"beez360-frc-franchisee-paris-dev-backoffice-webapp\"}[1h]))",
     "legendFormat": "BackOffice"
    },
    {
     "expr": "sum by(instance_name) (increase(appservice_request_count{instance_name=\"beez360-frc-franchisee-paris-dev-clickandcollect-webapp\"}[1h]))",
     "legendFormat": "Click&Collect"
    }
   ]
  },
  {
   "title": "Memory Working Set of webApps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "appservice_memory_working_set{instance_name=\"beez360-frc-franchisee-paris-dev-backoffice-webapp\"}",
     "legendFormat": "BackOffice"
    },
    {
     "expr": "appservice_memory_working_set{instance_name=\"beez360-frc-franchisee-paris-dev-clickandcollect-webapp\"}",
     "legendFormat": "Click&Collect"
    },
    {
     "expr": "appservice_memory_working_set{instance_name=\"beez360-frc-franchisee-paris-dev-api-webapp\"}",
     "legendFormat": "Api"
    }
   ]
  },
  {
   "title": "Nombre de erreur 5xx",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 15, "x": 3, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "appservice_http_5xx{instance_name=\"beez360-frc-franchisee-paris-dev-backoffice-webapp\"}",
     "legendFormat": "BackOffice"
    },
    {
     "expr": "appservice_http_5xx{instance_name=\"beez360-frc-franchisee-paris-dev-clickandcollect-webapp\"}",
     "legendFormat": "Click&Collect"
    },
    {
     "expr": "appservice_http_5xx{instance_name=\"beez360-frc-franchisee-paris-dev-api-webapp\"}",
     "legendFormat": "Api"
    }
   ]
  },
  {
   "title": "DataBases Infos",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgresql_active_connections{instance_name=\"beez360-frc-franchisee-paris-dev-psql-Flexible\"}",
     "legendFormat": "Active Connections "
    },
    {
     "expr": "postgresql_cpu_percent{instance_name=\"beez360-frc-franchisee-paris-dev-psql-Flexible\"}",
     "legendFormat": "Cpu consommation"
    },
    {
     "expr": "postgresql_storage_used{instance_name=\"beez360-frc-franchisee-paris-dev-psql-Flexible\"}",
     "legendFormat": "Stockage utilisé"
    }
   ]
  },
  {
   "title": "Memory consommation of Frontend & Backend",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "appplan_memory_percentage{instance_name=\"beez360-frc-franchisee-paris-dev-frontend-asp\"}",
     "legendFormat": "Frontend"
    },
    {
     "expr": "appplan_memory_percentage{instance_name=\"beez360-frc-franchisee-paris-dev-backend-asp\"}",
     "legendFormat": "Backend"
    }
   ]
  },
  {
   "title": "Cpu consommation Frontend & Backend",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "appplan_cpu_percentage{instance_name=\"beez360-frc-franchisee-paris-dev-backend-asp\"}",
     "legendFormat": "Backend"
    },
    {
     "expr": "appplan_cpu_percentage{instance_name=\"beez360-frc-franchisee-paris-dev-frontend-asp\"}",
     "legendFormat": "Frontend"
    }
   ]
  },
  {
   "title": "Pourcentage of Cpu Time of Sites",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 40 },
   "targets": [
    {
     "expr": "appservice_cpu_time{instance_name=\"beez360-frc-franchisee-paris-dev-clickandcollect-webapp\"}",
     "legendFormat": "Click&Collect"
    },
    {
     "expr": "appservice_cpu_time{instance_name=\"beez360-frc-franchisee-paris-dev-backoffice-webapp\"}",
     "legendFormat": "BackOffice"
    },
    {
     "expr": "appservice_cpu_time{instance_name=\"beez360-frc-franchisee-paris-dev-api-webapp\"}",
     "legendFormat": "Api"
    }
   ]
  },
  {
   "title": "Nombre de flux recus pour les WebApps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "appservice_bytes_received{instance_name=\"beez360-frc-franchisee-paris-dev-backoffice-webapp\"}",
     "legendFormat": "BackOffice"
    },
    {
     "expr": "appservice_bytes_received{instance_name=\"beez360-frc-franchisee-paris-dev-clickandcollect-webapp\"}",
     "legendFormat": "Click&Collect"
    },
    {
     "expr": "appservice_bytes_received{instance_name=\"beez360-frc-franchisee-paris-dev-api-webapp\"}",
     "legendFormat": "Api"
    }
   ]
  },
  {
   "title": "Nombre de flux envoyés pour les webApps",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "appservice_bytes_sent{instance_name=\"beez360-frc-franchisee-paris-dev-backoffice-webapp\"}",
     "legendFormat": "BackOffice"
    },
    {
     "expr": "appservice_bytes_sent{instance_name=\"beez360-frc-franchisee-paris-dev-clickandcollect-webapp\"}",
     "legendFormat": "Click&Collect"
    },
    {
     "expr": "appservice_bytes_sent{instance_name=\"beez360-frc-franchisee-paris-dev-api-webapp\"}",
     "legendFormat": "Api"
    }
   ]
  }
 ]
}