{
 "title": "Postgres Logs ",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "le nombre total de requêtes d'insertion dans tout les BD ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(DatabaseName) (rate({service=\"postgres\"} | json | label_format DatabaseName=properties_DatabaseName | unwrap properties_N_tup_ins [1h]))",
     "legendFormat": "Base de donnée : {{DatabaseName}}"
    }
   ]
  },
  {
   "title": "nombre de requetes par heure ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(properties_DatabaseName) (count_over_time({service=\"postgres\"} | json | line_format `{{.properties_DatabaseName}}` [1h]))",
     "legendFormat": "Base de donnée : {{properties_DatabaseName}}"
    }
   ]
  },
  {
   "title": "Postgres Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service=\"postgres\"}"
    }
   ]
  }
 ]
}