name: Terraform Azure Deployment

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID_MONITOR }}
          tenant-id: ${{ secrets.TENANT_ID_MONITOR }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID_MONITOR }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      # ---------- BOOTSTRAP BACKEND ----------
      - name: Terraform Bootstrap Init
        working-directory: bootstrap
        run: terraform init

      - name: Terraform Bootstrap Apply
        working-directory: bootstrap
        run: terraform apply -auto-approve

      # ---------- REAL STACK ----------
      - name: Terraform Init
        run: terraform init -reconfigure

      - name: Terraform Plan
        run: terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=terraform.tfvars
